<a href="https://colab.research.google.com/github/trieuduongle/SimVP-Simpler-yet-Better-Video-Prediction/blob/3d-patch-gan/3d-patch-gan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
!git clone https://github.com/trieuduongle/SimVP-Simpler-yet-Better-Video-Prediction.git '/content/drive/My Drive/Duong/SimVP/code'

fatal: destination path '/content/drive/My Drive/Duong/SimVP/code' already exists and is not an empty directory.


In [2]:
%cd '/content/drive/My Drive/Duong/SimVP/code'

/content/drive/My Drive/Duong/SimVP/code


In [ ]:
import torch
torch.cuda.device_count()
torch.cuda.is_available()
torch.cuda.current_device()
torch.cuda.device(0)
torch.cuda.get_device_name(0)

'Tesla T4'

In [3]:
!git fetch origin && git checkout 3d-patch-gan && git pull

Checking out files: 100% (15/15), done.
Switched to branch '3d-patch-gan'
Your branch is behind 'origin/3d-patch-gan' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Updating a621631..07bd716
Fast-forward
 3d-patch-gan.ipynb | 299 ++++++++++++++++++++++++++++++++++++++++++++++++-----
 1 file changed, 275 insertions(+), 24 deletions(-)


In [ ]:
!bash "./data/moving_mnist/download_mmnist.sh"

--2022-12-02 18:06:52--  http://www.cs.toronto.edu/~nitish/unsupervised_video/mnist_test_seq.npy
Resolving www.cs.toronto.edu (www.cs.toronto.edu)... 128.100.3.30
Connecting to www.cs.toronto.edu (www.cs.toronto.edu)|128.100.3.30|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 819200096 (781M)
Saving to: ‘mnist_test_seq.npy’

mnist_test_seq.npy  100%[===================>] 781.25M  9.28MB/s    in 41s     

2022-12-02 18:07:33 (19.1 MB/s) - ‘mnist_test_seq.npy’ saved [819200096/819200096]

--2022-12-02 18:07:33--  http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
Resolving yann.lecun.com (yann.lecun.com)... 172.67.171.76, 104.21.29.36, 2606:4700:3034::6815:1d24, ...
Connecting to yann.lecun.com (yann.lecun.com)|172.67.171.76|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9912422 (9.5M) [application/x-gzip]
Saving to: ‘train-images-idx3-ubyte.gz’

train-images-idx3-u 100%[===================>]   9.45M  61.6MB/s    in 0.2s    

2

In [ ]:
!ls

API		 main.py	     readme_figures		 utils.py
data		 mnist_test_seq.npy  README.md
environment.yml  model.py	     SimVP.ipynb
exp.py		 modules.py	     train-images-idx3-ubyte.gz


In [ ]:
!python main.py --batch_size 64

Use GPU: 0

device: 	cuda	
res_dir: 	./results	
ex_name: 	Debug	
use_gpu: 	True	
gpu: 	0	
seed: 	1	
batch_size: 	64	
val_batch_size: 	16	
data_root: 	./data/	
dataname: 	mmnist	
num_workers: 	8	
in_shape: 	[10, 1, 64, 64]	
hid_S: 	64	
hid_T: 	256	
N_S: 	4	
N_T: 	8	
groups: 	4	
epochs: 	51	
log_step: 	1	
lr: 	0.01	
>>>>>>>>>>>>>>>>>>>>>>>>>>>>  start <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
train loss: 0.0337: 100% 157/157 [00:44<00:00,  3.54it/s]
vali loss: 0.0310:  10% 63/625 [00:03<00:27, 20.68it/s]
vali mse:137.6444, mae:346.0001, ssim:0.4469, psnr:31.2841
Epoch: 1 | Train Loss: 0.0460 Vali Loss: 0.0336

Validation loss decreased (inf --> 0.033605).  Saving model ...
train loss: 0.0313: 100% 157/157 [00:37<00:00,  4.23it/s]
vali loss: 0.0286:  10% 63/625 [00:03<00:28, 19.47it/s]
vali mse:126.3827, mae:296.9196, ssim:0.5107, psnr:32.2142
Epoch: 2 | Train Loss: 0.0313 Vali Loss: 0.0309

Validation loss decreased (0.033605 --> 0.030855).  Saving model ...
train loss: 0.0283: 100% 157/157 [00:3

In [ ]:
!git pull && python interpolate.py

remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/trieuduongle/SimVP-Simpler-yet-Better-Video-Prediction
   55ab4a7..8c50ab2  colab      -> origin/colab
Updating 55ab4a7..8c50ab2
Fast-forward
 exp.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
Use GPU: 0

device: 	cuda	
res_dir: 	./results	
ex_name: 	Debug	
use_gpu: 	True	
gpu: 	0	
seed: 	1	
batch_size: 	16	
val_batch_size: 	16	
data_root: 	./data/	
dataname: 	mmnist	
num_workers: 	8	
in_shape: 	[10, 1, 64, 64]	
hid_S: 	64	
hid_T: 	256	
N_S: 	4	
N_T: 	8	
groups: 	4	
epochs: 	51	
log_step: 	1	
lr: 	0.01	
(16, 10, 1, 64, 64)
[[ 76  51  42 ...  69  65  66]
 [ 74  31  70 ...  32  67  80]
 [253  29  83 ...  40  40  55]
 ...
 [ 82  31  74 ...  49  71  57]
 [ 49  27  32 ...  44  35  56]
 [ 69  38  73 ...  71  76  92]]
(64, 64)
[[99

#Trainning with Moving MNIST dataset

In [16]:
!git pull

remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/trieuduongle/SimVP-Simpler-yet-Better-Video-Prediction
   2980080..6908366  3d-patch-gan -> origin/3d-patch-gan
Updating 2980080..6908366
Fast-forward
 gan.py | 3 +--
 1 file changed, 1 insertion(+), 2 deletions(-)


In [4]:
!pip install -r requirements.txt

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 107 kB 13.2 MB/s 
     |████████████████████████████████| 14.0 MB 70.9 MB/s 
  Attempting uninstall: scikit-image
    Found existing installation: scikit-image 0.18.3
    Uninstalling scikit-image-0.18.3:
      Successfully uninstalled scikit-image-0.18.3


In [9]:
!git checkout 3d-patch-gan

Already on '3d-patch-gan'
Your branch is up to date with 'origin/3d-patch-gan'.


In [ ]:
!python main.py \
  --res_dir './results/mnist/20221212-lan-hai-temporal-patch-gan-resume-epoch-1' \
  --data_root '/content/drive/My Drive/Duong/datasets/' \
  --dataname 'mmnist' \
  --num_workers 8 \
  --batch_size 32 \
  --val_batch_size 32 \
  --epochs 201 \
  --save_epoch_freq 5\
  --in_shape 10 1 64 64 \
  --pre_seq_length 10 \
  --aft_seq_length 10 \
  --image_channels 1

Use GPU: 0
including adv loss

device: 	cuda	
res_dir: 	./results/mnist/20221212-lan-hai-temporal-patch-gan-resume-epoch-1	
ex_name: 	Debug	
use_gpu: 	True	
gpu: 	0	
seed: 	1	
batch_size: 	32	
val_batch_size: 	32	
data_root: 	/content/drive/My Drive/Duong/datasets/	
dataname: 	mmnist	
num_workers: 	8	
in_shape: 	[10, 1, 64, 64]	
image_channels: 	1	
hid_S: 	64	
hid_T: 	256	
N_S: 	4	
N_T: 	8	
groups: 	4	
pre_seq_length: 	10	
aft_seq_length: 	10	
epochs: 	201	
log_step: 	1	
save_epoch_freq: 	5	
lr: 	0.01	
resume_path: 		
lr_D: 	0.0001	
gan_type: 	vanilla	
lambda_adv: 	0.005	
>>>>>>>>>>>>>>>>>>>>>>>>>>>>  start <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
train loss: 0.0353 - NonGAN loss: 0.0318 - GAN loss: 0.0035: 100% 313/313 [17:10<00:00,  3.29s/it]
vali loss: 0.0309:  10% 32/313 [00:13<02:00,  2.33it/s]
vali mse:129.0843, mae:316.1860, ssim:0.4988, psnr:31.9352
Epoch: 1 | Train Loss: 0.0424 - NonGAN loss: 0.0391 - GAN loss: 0.0033 Vali Loss: 0.0315 | Take 1051.1902 seconds

Validation loss decreas

In [ ]:
from API.dataloader_moving_mnist import load_data

train_loader, vali_loader, test_loader, data_mean, data_std =  load_data(9,10, '/content/drive/My Drive/Duong/datasets/', 1)

for batch_x, batch_y in train_loader:
  print(batch_x.size())
  break

torch.Size([9, 10, 1, 64, 64])


In [ ]:
!python main.py \
  --res_dir './results/mnist/20221213-lan-mot-model-dua-pytorch-gan' \
  --data_root '/content/drive/My Drive/Duong/datasets/' \
  --dataname 'mmnist' \
  --num_workers 8 \
  --batch_size 32 \
  --val_batch_size 32 \
  --epochs 201 \
  --save_epoch_freq 5\
  --in_shape 10 1 64 64 \
  --pre_seq_length 10 \
  --aft_seq_length 10 \
  --image_channels 1

Use GPU: 0

device: 	cuda	
res_dir: 	./results/mnist/20221213-lan-mot-model-dua-pytorch-gan	
ex_name: 	Debug	
use_gpu: 	True	
gpu: 	0	
seed: 	1	
batch_size: 	32	
val_batch_size: 	32	
data_root: 	/content/drive/My Drive/Duong/datasets/	
dataname: 	mmnist	
num_workers: 	8	
in_shape: 	[10, 1, 64, 64]	
image_channels: 	1	
hid_S: 	64	
hid_T: 	256	
N_S: 	4	
N_T: 	8	
groups: 	4	
pre_seq_length: 	10	
aft_seq_length: 	10	
epochs: 	201	
log_step: 	1	
save_epoch_freq: 	5	
lr: 	0.01	
resume_path: 		
lr_D: 	0.0001	
gan_type: 	vanilla	
lambda_adv: 	0.005	
>>>>>>>>>>>>>>>>>>>>>>>>>>>>  start <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
train loss: 0.0331 - NonGAN loss: 0.0318 - Raw GAN loss: 0.250117600 - Discriminator loss: 0.250004083: 100% 313/313 [16:43<00:00,  3.21s/it]
vali loss: 0.0309:  10% 32/313 [00:13<01:57,  2.40it/s]
vali mse:128.8880, mae:314.9059, ssim:0.5170, psnr:32.1023
(32, 10, 1, 64, 64)
Epoch: 1 | Train Loss: 0.0403 - NonGAN loss: 0.0391 - GAN loss: 0.250121111 - Discriminator loss: 0.250003

In [ ]:
!python main.py \
  --res_dir './results/mnist/20221215-lan-mot-model-dua-pytorch-gan-resume-epoch-26' \
  --data_root '/content/drive/My Drive/Duong/datasets/' \
  --resume_path './results/mnist/20221213-lan-mot-model-dua-pytorch-gan/Debug/checkpoints/26.pth' \
  --dataname 'mmnist' \
  --num_workers 8 \
  --batch_size 32 \
  --val_batch_size 32 \
  --epochs 201 \
  --save_epoch_freq 5\
  --in_shape 10 1 64 64 \
  --pre_seq_length 10 \
  --aft_seq_length 10 \
  --image_channels 1

Use GPU: 0

device: 	cuda	
res_dir: 	./results/mnist/20221215-lan-mot-model-dua-pytorch-gan-resume-epoch-26	
ex_name: 	Debug	
use_gpu: 	True	
gpu: 	0	
seed: 	1	
batch_size: 	32	
val_batch_size: 	32	
data_root: 	/content/drive/My Drive/Duong/datasets/	
dataname: 	mmnist	
num_workers: 	8	
in_shape: 	[10, 1, 64, 64]	
image_channels: 	1	
hid_S: 	64	
hid_T: 	256	
N_S: 	4	
N_T: 	8	
groups: 	4	
pre_seq_length: 	10	
aft_seq_length: 	10	
epochs: 	201	
log_step: 	1	
save_epoch_freq: 	5	
lr: 	0.01	
resume_path: 	./results/mnist/20221213-lan-mot-model-dua-pytorch-gan/Debug/checkpoints/26.pth	
lr_D: 	0.0001	
gan_type: 	vanilla	
lambda_adv: 	0.005	
resuming
>>>>>>>>>>>>>>>>>>>>>>>>>>>>  start <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
train loss: 0.0165 - NonGAN loss: 0.0153 - Raw GAN loss: 0.250081986 - Discriminator loss: 0.249997258: 100% 313/313 [17:11<00:00,  3.30s/it]
vali loss: 0.0149:  10% 32/313 [00:13<01:59,  2.35it/s]
vali mse:63.9472, mae:156.1166, ssim:0.8363, psnr:36.3589
(32, 10, 1, 64, 64)
Epo

In [13]:
import torch
torch.load('./results/mnist/20221213-lan-mot-model-dua-pytorch-gan/Debug/checkpoints/26.pth').keys()

dict_keys(['GENERATOR_STATE_DICT', 'GENERATOR_OPTIMIZER_STATE_DICT', 'DISCRIMINATOR_STATE_DICT', 'DISCRIMINATOR_OPTIMIZER_STATE_DICT'])

In [ ]:
!git pull && python interpolate.py \
  --data_root '/content/drive/My Drive/Duong/datasets/' \
  --resume_path './results/mnist/20221212-lan-hai-temporal-patch-gan-resume-epoch-1/Debug/checkpoints/3.pth' \
  --res_dir './results/mnist/20221212-lan-hai-temporal-patch-gan-resume-epoch-1'

Already up to date.
Use GPU: 0
Traceback (most recent call last):
  File "interpolate.py", line 18, in <module>
    main()
  File "interpolate.py", line 14, in main
    exp = Exp(args)
  File "/content/drive/MyDrive/Duong/SimVP/code/exp.py", line 24, in __init__
    self._preparation()
  File "/content/drive/MyDrive/Duong/SimVP/code/exp.py", line 62, in _preparation
    self._build_model()
  File "/content/drive/MyDrive/Duong/SimVP/code/exp.py", line 77, in _build_model
    raise (ValueError('Resume path does not exist'))
ValueError: Resume path does not exist


# Traning with KTH dataset

In [ ]:
!unzip '/content/drive/My Drive/Duong/datasets/kth.zip' -d '/content/drive/My Drive/Duong/datasets/kth'

Archive:  /content/drive/My Drive/Duong/datasets/kth.zip
mapname:  conversion of  failed
 extracting: /content/drive/My Drive/Duong/datasets/kth/dataloader_kth.py  
 extracting: /content/drive/My Drive/Duong/datasets/kth/test_data_gzip.hkl  
 extracting: /content/drive/My Drive/Duong/datasets/kth/train_data_gzip.hkl  
 extracting: /content/drive/My Drive/Duong/datasets/kth/test_indices_gzip.hkl  
 extracting: /content/drive/My Drive/Duong/datasets/kth/train_indices_gzip.hkl  


In [ ]:
!pip install hickle

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 107 kB 4.8 MB/s 


In [ ]:
!python main.py \
  --res_dir './results/20221203' \
  --data_root '/content/drive/My Drive/Duong/datasets/kth/' \
  --dataname 'kth' \
  --num_workers 1 \
  --batch_size 8 \
  --in_shape 10 1 128 128

Use GPU: 0
exist
tcmalloc: large alloc 16681664512 bytes == 0x6478000 @  0x7f8fcffde1e7 0x7f8f5ffd414e 0x7f8f6002c745 0x7f8f5ffd79c8 0x5d7f65 0x560200 0x55e571 0x4eae40 0x7f8f2ea70f05 0x5d813c 0x4ff485 0x46eb22 0x59daf9 0x5176d9 0x55fa11 0x5d7c18 0x49ec69 0x5d7c18 0x49ec69 0x55e571 0x5d7cf1 0x49caa1 0x5d7c18 0x49ca7c 0x55e571 0x5d7cf1 0x49ec69 0x55e571 0x5d7cf1 0x5d77c6 0x561051
tcmalloc: large alloc 16681664512 bytes == 0x3fc394000 @  0x7f8fcffde1e7 0x7f8f5ffd414e 0x7f8f60030166 0x7f8f60022665 0x7f8f600d3640 0x5aa114 0x49ced5 0x5d7c18 0x49ec69 0x5d7c18 0x49ec69 0x55e571 0x5d7cf1 0x49caa1 0x5d7c18 0x49ca7c 0x55e571 0x5d7cf1 0x49ec69 0x55e571 0x5d7cf1 0x5d77c6 0x561051 0x5d7c18 0x49ca7c 0x5d7c18 0x49ca7c 0x55e858 0x5d7cf1 0x5d9412 0x586306
tcmalloc: large alloc 9808510976 bytes == 0x63f6000 @  0x7f8fcffde1e7 0x7f8f5ffd414e 0x7f8f6002c745 0x7f8f5ffd79c8 0x5d7f65 0x560200 0x55e571 0x4eae40 0x7f8f2ea70f05 0x5d813c 0x4ff485 0x46eb22 0x59daf9 0x5176d9 0x55fa11 0x5d7c18 0x49ec69 0x5d7c18 0x49

In [ ]:
!ls '/content/drive/My Drive/Duong/datasets/kth'

dataloader_kth.py   test_indices_gzip.hkl  train_indices_gzip.hkl
test_data_gzip.hkl  train_data_gzip.hkl


#Try to run model

In [ ]:
!git pull

remote: Enumerating objects: 51, done.
remote: Counting objects: 100% (51/51), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 41 (delta 27), reused 22 (delta 12), pack-reused 0
Unpacking objects: 100% (41/41), done.
From https://github.com/trieuduongle/SimVP-Simpler-yet-Better-Video-Prediction
   f07a3d2..36c3530  colab      -> origin/colab
Updating f07a3d2..36c3530
Fast-forward
 API/dataloader.py              |   9 +-
 API/dataloader_kth.py          |   4 +
 API/dataloader_moving_mnist.py |   4 +-
 SimVP.ipynb                    | 665 +++++++++++++++++++++++++++++++++++++++--
 create_parser.py               |  45 +++
 exp.py                         |  10 +-
 fake_training.py               | 131 ++++++++
 interpolate.py                 |   9 +-
 main.py                        |   2 +
 requirements.txt               |   4 +-
 10 files changed, 847 insertions(+), 36 deletions(-)
 create mode 100644 create_parser.py
 create mode 100644 fake_training.py


In [ ]:
!python main.py \
  --res_dir './results/fake_training/' \
  --data_root '/content/drive/My Drive/Duong/datasets/' \
  --dataname 'mmnist' \
  --num_workers 8 \
  --batch_size 16 \
  --save_epoch_freq 2\
  --in_shape 10 1 64 64

Use GPU: 0

device: 	cuda	
res_dir: 	./results/fake_training/	
ex_name: 	Debug	
use_gpu: 	True	
gpu: 	0	
seed: 	1	
batch_size: 	16	
val_batch_size: 	16	
data_root: 	/content/drive/My Drive/Duong/datasets/	
dataname: 	mmnist	
num_workers: 	8	
in_shape: 	[10, 1, 64, 64]	
hid_S: 	64	
hid_T: 	256	
N_S: 	4	
N_T: 	8	
groups: 	4	
epochs: 	51	
log_step: 	1	
save_epoch_freq: 	2	
lr: 	0.01	
resume_path: 		
>>>>>>>>>>>>>>>>>>>>>>>>>>>>  start <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  0% 0/625 [00:00<?, ?it/s]longger
train loss: 0.1219:   0% 1/625 [00:05<1:00:43,  5.84s/it]longger
train loss: 0.5743:   0% 2/625 [00:07<32:35,  3.14s/it]  longger
train loss: 0.1668:   0% 3/625 [00:08<23:36,  2.28s/it]longger
train loss: 0.0751:   1% 4/625 [00:09<19:24,  1.88s/it]longger
train loss: 0.1162:   1% 5/625 [00:10<17:05,  1.65s/it]longger
train loss: 0.1168:   1% 6/625 [00:12<15:41,  1.52s/it]longger
train loss: 0.0851:   1% 7/625 [00:13<14:48,  1.44s/it]longger
train loss: 0.0640:   1% 8/625 [00:14<14:14,  1.38s